[package]
name = "nzsc_single_player"
version = "0.5.1"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]

repository = "https://github.com/nzsc-org/nzsc_single_player"

license = "MIT"

description = "A complete implementation of NZSC written in Rust."
